spring.application.name=ventas-ferreteria
server.port=9000
spring.datasource.url=jdbc:mysql://192.168.1.10:3306/ferreteria_db?serverTimezone=UTC
spring.datasource.username=roberto
spring.datasource.password=root


#spring.jpa.show-sql=true
#spring.jpa.generate-ddl=true
#spring.jpa.hibernate.ddl-auto=create   
#spring.jpa.hibernate.ddl-auto=update  
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl



productos.auth.url=http://localhost:8080/realms/ContactosReino/protocol/openid-connect/token
productos.auth.user=admin
productos.auth.pass=ad123
productos.auth.client.id=login
productos.auth.grandt.type=password

#propiedas para cliente eureka
eureka.client.serviceUrl.defaultZone=http://admin:admeureka123@localhost:8761/eureka