spring:
  application:
    name: productos-ferreteria
  datasource:
    url: jdbc:mysql://${IP_HOST}:${PORT_DB}/ferreteria_db?serverTimezone=UTC
    username: ${USER_DB}
    password: ${PASS_DB}
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${IP_HOST}:8080/realms/ContactosReino
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
server:
  port: 8000
keycloak:
  clientId: login
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admeureka123@${IP_HOST}:8761/eureka
  instance:
    hostname: ${IP_HOST}
    non-secure-port: ${PORT_HOST}
